import type { Metadata } from "next";
import LocalFont from "next/font/local";
import { ThemeProvider } from "@/components/theme/theme-provider"
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const sans = LocalFont({
  variable: "--font-sans",
  src: [
    {
      path: 'fonts/bold.woff2',
      weight: '700',
    },
    {
      path: 'fonts/medium.woff2',
      weight: '500',
    },
    {
      path: 'fonts/regular.woff2',
      weight: '400',
    },
  ]
})

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
        {/* rest of your scripts go under */}
      </head>
      <body
        className={`${sans.variable} ${geistMono.variable} antialiased max-w-screen-2xl mx-auto`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
