import "./globals.css";
import type { Metadata } from "next";
import LocalFont from "next/font/local";
import Topbar from "@/components/nav/topbar";
import { Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme/theme-provider";

const sans = LocalFont({
  variable: "--font-sans",
  src: [
    {
      path: 'bold.woff2',
      weight: '700',
    },
    {
      path: 'medium.woff2',
      weight: '500',
    },
    {
      path: 'regular.woff2',
      weight: '400',
    },
  ]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <script
          async
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        /> */}
      </head>
      <body
        className={`${sans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Topbar />
          <main className="relative size-full min-h-[calc(100dvh-120)] p-5 md:p-8">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
