import "./globals.css";
import type { Metadata } from "next";
import LocalFont from "next/font/local"
import { Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/nav/app-sidebar";
import Topbar from "@/components/nav/topbar";

const sans = LocalFont({
  variable: "--font-sans",
  src: [
    {
      path: 'bold.woff2',
      weight: '700',
    },
    {
      path: 'medium.woff2',
      weight: '500',
    },
    {
      path: 'regular.woff2',
      weight: '400',
    },
  ]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="bg-background size-full min-h-dvh">
              <Topbar />
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
